FROM node:14

SHELL ["/bin/bash", "-c"]

ENV NODE_ENV development

WORKDIR /app

ADD . ./

RUN npm i -g npm@7.7.5

RUN npm i

RUN chmod +x docker-entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["docker-entrypoint.sh"]
