version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: sh -c 'npm run dev'
    ports:
      - 3000:3000
    volumes:
     - '.:/app'
    environment:
     - CHOKIDAR_USEPOLLING=true
  backend:
    image: blogbackend:latest
    ports:
      - 3003:3003
